/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About.vue')['default']
    CheckToken: typeof import('./src/components/CheckToken.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    FileReader: typeof import('./src/components/FileReader.vue')['default']
    Greet: typeof import('./src/components/Greet.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Working: typeof import('./src/components/Working.vue')['default']
  }
}
